import mongoose, { Schema } from "mongoose";

const GenitalesLaboratorio = new Schema({
    shape: String,
    skin_Genitals: String,
    mass: String,
    lymph_nodes: String,
    pain: String,
    structure: String,
    skin_Sup: String,
    pulse: String,
    reflexes: String,
    sensitivity: String,
    muscular_strength: String,
    other_characteristics_Sup: String,
    hands: String,
    nails: String,
    structure: String,
    skin_Inf: String,
    pulse_inf: String,  
    reflexes_inf: String,
    sensitivity_inf: String,
    muscular_strength_inf: String,
    other_characteristic_Inf: String,
    feet: String,
    nails_inf: String,
    exploration_note_Sup_Inf: String,
    appearance: String,
    sensitivity_sup: String,
    emotions: String,
    motility: String,
    motor_behavior: String,
    coordination: String,
    intellectual_function: String,
    reflexes_psi: String,
    attention: String,
    balance: String,
    judgment: String,
    others: String,
    association_of_ideas: String,
    orientation: String,
    memory: String,
    language: String,
    exploration_note_Psi: String,
    cbc_complete_blood_count: String,
    qs_quick_screening: String,
    blood_type_and_rh_factor: String,
    ego: String,
    audiometry: String,
    chest_xray: String,
    spine_xray: String,
    pharyngeal_swab: String,
    stool_test: String,
    xii_diagnosis: String,
    xiii_treatment: String,
    xiv_comments: String

})

export default mongoose.model('examenLaboratorioGenitales', GenitalesLaboratorio)


