import mongoose, { Schema } from "mongoose";

const PhysicalExploration = new Schema({
    peso: Number,
    weight: String,
    size: String,
    temp: String,
    pulse: String,
    ideal_weight: String,
    bodily_integrity: String,
    march: String,
    abnormal_movements: String,
    specify_body: String,
    specify_abnormalities: String,
    ears: String,
    ear_canal: String,
    tympanum: String,
    audition: String,
    nose: String,
    septum: String,
    crinnes: String,
    mucosa: String,
    secretions: String,
    mouth: String,
    mucous: String,
    gums: String,
    teeth: String,
    tongue: String,
    pharynx: String,
    tonsils: String,
    eyes: String,
    eyelids: String,
    annexes: String,
    conjunctiva: String,
    scleratic: String,
    previous_camera: String,
    fundus: String,
    pupils: String,
    eye_reflexes: String,
    visual_acuity: String,
    right_eye: String,
    left_eye: String,
    od_with_correction: String,
    oi_with_correction: String,
    dentist: String,
    lack: String,
    clogged: String,
    malformation: String,
    mmmppciiiicppmmm_top: String,
    mmmppciiiicppmmm_bottom: String,
    exploration_note: String,
    skin: String,
    pulse_carotid: String,
    ganglia: String,
    cervical: String,
    thyroid: String,
    exploration_note_: String,
    thoracic_: String,
    skin_: String,
    breasts_and_nipples: String,
    breathing_movements: String,
    lung_fields: String,
    heart_rate: String,
    noise_intensity: String,
    features_heartbeat: String,
    exploration_note_T: String,
    abdomen: String,
    skin_abd: String,
    form: String,
    pain: String,
    consistency: String,
    visceromegaly: String,
    peristalsis: String,
    exploration_note_abd: String,
    user : {
        type: mongoose.Schema.Types.ObjectId,
        require: true,
    },
}, {
timestamps: true
})

export default mongoose.model('exploracion_Fisica', PhysicalExploration)

